### ISSUE TITLE
wrong argument name 'serviceuuid'

### ISSUE THREAD

**Issue by Shik1266** [juliansteenbakker/flutter_ble_peripheral#153]
version 1.2.1

advertise_data.dart :27
**'serviceUuid'**: instance.serviceUuid,

SwiftFlutterBlePeripheralPlugin.swift :61
            uuid: map?["**serviceUuid**"] as? String ,

please check argument name uuid -> serviceUuid

FlutterBlePeripheralPlugin.kt :159
 (arguments**["uuid"]** as String?)?.let { advertiseData.addServiceUuid(ParcelUuid(UUID.fromString(it))) }

**Comment by juliansteenbakker** [comment]
Merged, thanks for the fix!
