### ISSUE TITLE
flutter run command giving error!

### ISSUE THREAD

**Issue by crackerboy** [juliansteenbakker/flutter_ble_peripheral#29]
On VScode IDE flutter console giving the following error:

> Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>`
> and then move the dart code, assets and pubspec.yaml to the new project.

Any idea?

**Comment by juliansteenbakker** [comment]
That seems weird. I have updated gradle so maybe that will resolve the problem.
