### ISSUE TITLE
Android 12 Support

### ISSUE THREAD

**Issue by shobhit14gupta** [juliansteenbakker/flutter_ble_peripheral#49]
When the new release will be publish with the support of Android 12?

**Comment by juliansteenbakker** [comment]
I am still working on improvements so stay tuned.

**Comment by nuunoo1977** [comment]
Hi @juliansteenbakker , any news about this? Thank you very much

**Comment by juliansteenbakker** [comment]
Sorry for all the delay. I have published v0.6.0 with Android 12 support.
